"""created table

Revision ID: 06a78c7734f5
Revises: 
Create Date: 2023-06-20 14:30:24.911329

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a78c7734f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('imageLink', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
